### ISSUE TITLE
Does broccoli-esnext no longer exist?

### ISSUE THREAD

**Issue by rsperberg** [addyosmani/es6-tools#62]
The link (github.com/shinnn/broccoli-esnext) ends up at github.com/shinnn/modify-event and there's no broccoli-esnext repository.

**Comment by sindresorhus** [comment]
@shinnn

**Comment by shinnn** [comment]
I [deprecated](https://www.npmjs.com/package/broccoli-esnext) it since [the upstream project](https://github.com/esnext/esnext/commit/cf9f957b64bcf3eb3122ee2521549e6def501656) was deprecated by the author.

**Comment by arthurvr** [comment]
Isn't it stange that GitHub redirects that to an unrelated repo?

>  since the upstream project was deprecated by the author.

Yeah, we should probably remove all esnext things from the list, though.

**Comment by shinnn** [comment]
> Isn't it stange that GitHub redirects that to an unrelated repo?

Because of my laziness I overwrote broccoli-esnext repo with the other project, instead of creating a new repo. I should have created a new one.
